export const PICTURES_LOADING = 'PICTURES_LOADING';
export const ADD_PICTURES = 'ADD_PICTURES';
export const PICTURES_FAILED = 'PICTURES_FAILED';
export const NETWORKS_LOADING = 'NETWORKS_LOADING';
export const ADD_NETWORKS = 'ADD_NETWORKS';
export const NETWORKS_FAILED = 'NETWORKS_FAILED';